### ISSUE TITLE
Releases are bundled with the source code.

### ISSUE THREAD

**Issue by lswank** [bob0bob/ARX#22]
This increases the size of the Git repo and is generally not great practice. There's a nice releases section here in Github where you can release put those without mangling up the Git repo. :) Lots of fans of the AR series. I'm sure others would love to help!

**Comment by bob0bob** [comment]
Thanks.  I'm not planning on anymore "C" updates.  It will not be Java and only way to get them is through.  LandBeyond.net  for now.  Its not out yet.
