### ISSUE TITLE
Repository does not contain any license information.

### ISSUE THREAD

**Issue by lswank** [bob0bob/ARX#23]
I'd love to look at contributing. Is this "open" closed source? Not sure what license contributions would fall under.

**Comment by bob0bob** [comment]
Right now it is closed.  The "C" version is.  I converted it to Java using LWJGL and that is closed.   I've completed a complete redo of the "The City".   I'm in the middle of testing.  I'm not using GitHub for the Java.  I just have github installed on my local server where I dealing with source code.
